In [39]:
import pandas as pd
import numpy as np

In [40]:
s = pd.Series([3, -5, 7, 4], index=['a', 'b', 'c', 'd'])
print(s)

a    3
b   -5
c    7
d    4
dtype: int64

In [41]:
data = { 
    'Country': ['Belgium', 'India', 'Brazil'], 
    'Capital': ['Brussels', 'New Delhi', 'Brasilia'],
    'Population': [11190846, 1303171035, 207847528]
    }

df = pd.DataFrame(data, columns=['Country', 'Capital', 'Population'])
display(df)

   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528

### **DROPPING**

In [42]:
s.drop(['a', 'c'], inplace=True)
print(s)

b   -5
d    4
dtype: int64

In [43]:
df.drop('Country', axis=1)
display(df)

   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528

### **ASKING FOR HELP**

In [44]:
# help(pd.Series.loc)

In [45]:
# Sort by the values along an axis
df.sort_index()
df

   Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528

In [46]:
# Sort by labels along an axis
df.sort_values(by='Population', ascending=False, inplace=True)
df

   Country    Capital  Population
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528
0  Belgium   Brussels    11190846

In [47]:
# Assign ranks to entries
df.rank()

   Country  Capital  Population
1      3.0      3.0         3.0
2      2.0      1.0         2.0
0      1.0      2.0         1.0

# **TEST**

In [56]:
# np.array([[3, -5, 7, 4], [1, 2, 3, 4], [10, 20, 30, 40]]).T
serie = pd.DataFrame([[3, -5, 7, 4], [1, 2, 3, 4], [10, 20, 30, 40]])
serie

    0   1   2   3
0   3  -5   7   4
1   1   2   3   4
2  10  20  30  40

In [57]:
np.array(serie.mean())

array([ 4.66666667,  5.66666667, 13.33333333, 16.        ])

In [60]:
tups = pd.DataFrame([(3, -5, 7, 4), (1, 2, 3, 4), (10, 20, 30, 40)])
tups.sort_values(by=3)

    0   1   2   3
0   3  -5   7   4
1   1   2   3   4
2  10  20  30  40